<?php
/**
 * PaymentprocessorPerformPaymentResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Paymentprocessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Processor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Paymentprocessor\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PaymentprocessorPerformPaymentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentprocessorPerformPaymentResponse
 * @package     GeminiCommerce\Paymentprocessor
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentprocessorPerformPaymentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentprocessorPerformPaymentResponse"
     */
    public function testPaymentprocessorPerformPaymentResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_upfront"
     */
    public function testPropertyIsUpfront()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
